### ISSUE TITLE
[BUG] Can't compile with qt-6.10/c++20

### ISSUE THREAD

**Issue by PPN-SD** [bibletime/bibletime#539]
### Acknowledgments

- [x] I understand this form is for software feedback only, not for issues related to specific works like Bibles, commentaries, or books, nor for content provider-related concerns.
- [x] I have searched the issue tracker and confirm this issue has not already been reported, or that reopening an existing issue would not be appropriate.

### Bug description

I can't compile with c++20 allowed by qt-6.10:

```
In file included from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/ZNV6MPGS4G/../../../bibletime-3.2.0/src/backend/drivers/cswordbiblemoduleinfo.h:19,
                 from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/ZNV6MPGS4G/moc_cswordbiblemoduleinfo.cpp:9,
                 from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/mocs_compilation.cpp:10:
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/ZNV6MPGS4G/../../../bibletime-3.2.0/src/backend/drivers/../keys/cswordversekey.h: In function ‘bool operator<=>(const CSwordVerseKey&, const CSwordVerseKey&)’:
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/ZNV6MPGS4G/../../../bibletime-3.2.0/src/backend/drivers/../keys/cswordversekey.h:83:46: error: cannot convert ‘std::common_comparison_category_t<std::strong_ordering, std::strong_ordering, std::strong_ordering, std::strong_ordering, std::strong_ordering>’ {aka ‘std::strong_ordering’} to ‘bool’ in return
   83 |         BibleTime_CSwordVerseKey_DEFINE_COMP(<=>)
      |                                              ^
      |                                              |
      |                                              std::common_comparison_category_t<std::strong_ordering, std::strong_ordering, std::strong_ordering, std::strong_ordering, std::strong_ordering> {aka std::strong_ordering}
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/ZNV6MPGS4G/../../../bibletime-3.2.0/src/backend/drivers/../keys/cswordversekey.h:78:62: note: in definition of macro ‘BibleTime_CSwordVerseKey_DEFINE_COMP’
   78 |                                   lhs.verse(), lhs.suffix()) op \
      |                                                              ^~
In file included from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/models/btmoduletextmodel.h:22,
                 from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/moc_btmoduletextmodel.cpp:9,
                 from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/mocs_compilation.cpp:16:
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/models/../keys/cswordtreekey.h: In function ‘bool operator<=>(const CSwordTreeKey&, const CSwordTreeKey&)’:
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/models/../keys/cswordtreekey.h:57:45: error: cannot convert ‘std::strong_ordering’ to ‘bool’ in return
   57 |         BibleTime_CSwordTreeKey_DEFINE_COMP(<=>)
      |                                             ^
      |                                             |
      |                                             std::strong_ordering
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/models/../keys/cswordtreekey.h:55:35: note: in definition of macro ‘BibleTime_CSwordTreeKey_DEFINE_COMP’
   55 |             { return lhs.offset() op rhs.offset(); }
      |                                   ^~
ninja: build stopped: subcommand failed.
rivers/../keys/cswordversekey.h:78:62: note: in definition of macro ‘BibleTime_CSwordVerseKey_DEFINE_COMP’
   78 |                                   lhs.verse(), lhs.suffix()) op \
      |                                                              ^~
rivers/../keys/cswordversekey.h:78:62: note: in definition of macro ‘BibleTime_CSwordVerseKey_DEFINE_COMP’
   78 |                                   lhs.verse(), lhs.suffix()) op \
      |                                                              ^~
In file included from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibleti
me-3.2.0/src/backend/models/btmoduletextmodel.h:22,
                 from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/moc_btmoduletext
model.cpp:9,
                 from /var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/mocs_compilation.cpp:16:
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/m
odels/../keys/cswordtreekey.h: In function ‘bool operator<=>(const CSwordTreeKey&, const CSwordTreeKey&)’:
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/m
odels/../keys/cswordtreekey.h:57:45: error: cannot convert ‘std::strong_ordering’ to ‘bool’ in return
   57 |         BibleTime_CSwordTreeKey_DEFINE_COMP(<=>)
      |                                             ^
      |                                             |
      |                                             std::strong_ordering
/var/tmp/portage/app-text/bibletime-3.2.0/work/bibletime-3.2.0_build/bibletime_autogen/PQRTCD6VTJ/../../../bibletime-3.2.0/src/backend/m
odels/../keys/cswordtreekey.h:55:35: note: in definition of macro ‘BibleTime_CSwordTreeKey_DEFINE_COMP’
   55 |             { return lhs.offset() op rhs.offset(); }
      |                                   ^~
```

It works by forcing c++17

### Steps to reproduce

Build bibletime with c++20

### Expected behavior

Build

### Actual behavior

Can't compile

### BibleTime version

3.2.0

### How did you install BibleTime?

Manually built from source

### OS version

Gentoo gcc-16

**Comment by jaakristioja** [comment]
Please provide more information: what is your build environment (distro) and CMake version. What commands did you run to start the build? If possible, please include the full log for the `cmake` and `make VERBOSE=1` invocations (the `VERBOSE=1` is needed to show the `g++` command line arguments).

The build system should automatically force the use of C++17 in [cmake/BTApplication.cmake:63](https://github.com/bibletime/bibletime/blob/v3.2.0/cmake/BTApplication.cmake#L63).

**Comment by jaakristioja** [comment]
> The build system should automatically force the use of C++17 in [cmake/BTApplication.cmake:63](https://github.com/bibletime/bibletime/blob/v3.2.0/cmake/BTApplication.cmake#L63).

Aha, this doesn't actually force C++17, but requires C++17 or later ([doc](https://cmake.org/cmake/help/v4.2/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#high-level-meta-features-indicating-c-standard-support)). Anyway, I can reproduce this with on Gentoo with GCC 15 as well if I change the minimum requirement to C++20.
