### ISSUE TITLE
[BUG] Fails to compile with sword 1.8.1

### ISSUE THREAD

**Issue by jaimeMF** [bibletime/bibletime#498]
**Bug description**
I am trying to upgrade the bibletime package in openSUSE to version 3.1.0. It is giving me a compilation error which I also get when trying to build it from Qt Creator:
```
/usr/bin/g++ -DBT_VERSION=\"3.1.0+29c8a6a399997e6a54eab8c096c0e46584eb4fa8\" -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_UP_TO=0x060500 -DQT_GUI_LIB -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_XML_LIB -I[...]/bibletime/build-bibletime-Desktop-Debug/bibletime_backend_autogen/include -I/usr/lib64 -I[...]/bibletime/build-bibletime-Desktop-Debug -I/usr/include/sword -I[...]/bibletime/bibletime/src/frontend/display/modelview -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6 -isystem /usr/include/qt6/QtCore -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtXml -ggdb -Wall -Wextra -fPIE -fexceptions -Walloca -Wextra-semi -Wformat=2 -Wformat-signedness -Wfloat-equal -Wlogical-op -Wno-packed -Wno-padded -Wno-switch-enum -Wpointer-arith -Wsuggest-override -Wunused-parameter -Wzero-as-null-pointer-constant -fasynchronous-unwind-tables -fcf-protection=full -fstack-clash-protection -fstack-protector-strong -pipe -MD -MT CMakeFiles/bibletime_backend.dir/src/backend/btinstallmgr.cpp.o -MF CMakeFiles/bibletime_backend.dir/src/backend/btinstallmgr.cpp.o.d -o CMakeFiles/bibletime_backend.dir/src/backend/btinstallmgr.cpp.o -c [...]/bibletime/bibletime/src/backend/btinstallmgr.cpp
[...]/bibletime/bibletime/src/backend/btinstallmgr.cpp: In constructor 'BtInstallMgr::BtInstallMgr(QObject*)':
[...]/bibletime/bibletime/src/backend/btinstallmgr.cpp:75:9: error: 'setTimeoutMillis' was not declared in this scope
   75 |         setTimeoutMillis(0);
      |         ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/bibletime_backend.dir/build.make:253: CMakeFiles/bibletime_backend.dir/src/backend/btinstallmgr.cpp.o] Error 
```

On openSUSE the sword version is still 1.8.1, where the setTimeoutMillis method is not available yet. From what I have found (for example https://old.reddit.com/r/cpp/comments/139b5wt/code_in_ifconstexpr_branch_not_taken_causing/ ), even if HasSetTimeoutMillis<BtInstallMgr>::value evaluates to false in the `if constexpr` check, the body inside the if is checked. The `if constexp` can be replace with a call like `trySetTimeoutMillis(this, 0);` where trySetTimeoutMillis is defined as a template:
```c++
template <typename T>
void trySetTimeoutMillis(T *mgr, long timeoutMillis) {
    if constexpr (HasSetTimeoutMillis<T>::value) {
        mgr->setTimeoutMillis(timeoutMillis);
    }
}
```

It fixes the compilation error. I currently cannot test that the application runs because I am affected by #497 .

**System information:**
 - OS and OS version: openSUSE Tumbleweed
 - BibleTime Version: 3.1.0
 - How BibleTime was installed : compiled from source code
 - (If compiled from source) Sword Version: 1.8.1
 - (If compiled from source) Qt Version: 6.8.2

**Comment by jaakristioja** [comment]
Thank you for reporting this and your analysis on the issue! 

This should now be fixed by commit 0be2c8854eba81b94dbf81289d57ec50ab2b6ca4 in the stable-3.1 branch and by commit 484118926fe9ef2e564897c360111a0a8adcd352 in the master branch. Closing.

**Comment by jaimeMF** [comment]
Thank you.
